# Generated by Django 3.2 on 2023-06-13 13:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ieqtests.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_code', models.CharField(db_index=True, default=ieqtests.core.models.generate_code, editable=False, max_length=10, unique=True, verbose_name='Уникальный логин-код')),
            ],
            options={
                'verbose_name': 'Логин',
                'verbose_name_plural': 'Логины',
            },
        ),
        migrations.CreateModel(
            name='IQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время прохождения теста')),
                ('results', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Результаты IQ-теста')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_iq', to='core.test')),
            ],
            options={
                'verbose_name': 'IQ-тест',
                'verbose_name_plural': 'IQ-тесты',
            },
        ),
        migrations.CreateModel(
            name='EQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время прохождения теста')),
                ('results', models.CharField(max_length=5, verbose_name='Результаты EQ-теста')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_eq', to='core.test')),
            ],
            options={
                'verbose_name': 'EQ-тест',
                'verbose_name_plural': 'EQ-тесты',
            },
        ),
    ]
